### ISSUE TITLE
Project: Totally Testable

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/awsaml#32]
Awsaml doesn't currently have any automated testing around it. This creates a barrier to entry for contributors, since it's hard to know if your changes broke anything. We should set up automated tests for Awsaml and have them run by [Travis CI](https://travis-ci.org/) when pull requests are created.

Issues related to this project are filed under the "[totally-testable](https://github.com/rapid7/awsaml/milestones/totally-testable)" milestone.

**Comment by tquetano-r7** [comment]
You should consider using [tape](https://github.com/substack/tape) as your unit testing setup. For nodejs development it doesn't require a test harness when running the tests (just regular node scripts), and if you bolster tape with [proxyquire](https://github.com/thlorenz/proxyquire) and [sinon](https://github.com/sinonjs/sinon) you can handle a lot of your integration testing as well. 

I only call this out because picking these up are way simpler than a kitchen sink setup like Mocha or Jasmine, and its an alternative worth considering. I use them and it is quite a pleasure. :smile:
